source "https://rubygems.org"

#gem "berkshelf", github: "berkshelf/berkshelf"
gem 'berkshelf', git: 'git@github.com:berkshelf/berkshelf.git', branch: '2-0-stable'

gem 'knife-solo'
gem 'chef', '>= 11.8.2'
gem 'foodcritic'

gem 'knife-solo_data_bag'
